// stockData.js
export const stockData = [
    { symbol: 'AAPL', name: 'Apple Inc.' },
    { symbol: 'MSFT', name: 'Microsoft Corporation' },
    { symbol: 'GOOGL', name: 'Alphabet Inc. Class A' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.' },
    { symbol: 'NVDA', name: 'NVIDIA Corporation' },
    { symbol: 'META', name: 'Meta Platforms Inc.' },
    { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B' },
    { symbol: 'TSLA', name: 'Tesla Inc.' },
    { symbol: 'LLY', name: 'Eli Lilly and Company' },
    { symbol: 'V', name: 'Visa Inc.' },
    { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
    { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
    { symbol: 'JNJ', name: 'Johnson & Johnson' },
    { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
    { symbol: 'MA', name: 'Mastercard Inc.' },
    { symbol: 'PG', name: 'Procter & Gamble Company' },
    { symbol: 'HD', name: 'Home Depot Inc.' },
    { symbol: 'CVX', name: 'Chevron Corporation' },
    { symbol: 'AVGO', name: 'Broadcom Inc.' },
    { symbol: 'ABBV', name: 'AbbVie Inc.' },
    { symbol: 'MRK', name: 'Merck & Co. Inc.' },
    { symbol: 'PEP', name: 'PepsiCo Inc.' },
    { symbol: 'KO', name: 'Coca-Cola Company' },
    { symbol: 'COST', name: 'Costco Wholesale Corporation' },
    { symbol: 'BAC', name: 'Bank of America Corp' },
    { symbol: 'WMT', name: 'Walmart Inc.' },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
    { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
    { symbol: 'ABT', name: 'Abbott Laboratories' },
    { symbol: 'MCD', name: "McDonald's Corporation" },
    { symbol: 'CRM', name: 'Salesforce Inc.' },
    { symbol: 'ACN', name: 'Accenture plc' },
    { symbol: 'DHR', name: 'Danaher Corporation' },
    { symbol: 'NEE', name: 'NextEra Energy Inc.' },
    { symbol: 'LIN', name: 'Linde plc' },
    { symbol: 'ADBE', name: 'Adobe Inc.' },
    { symbol: 'TXN', name: 'Texas Instruments Inc.' },
    { symbol: 'VZ', name: 'Verizon Communications Inc.' },
    { symbol: 'PM', name: 'Philip Morris International Inc.' },
    { symbol: 'CMCSA', name: 'Comcast Corporation' },
    { symbol: 'NKE', name: 'Nike Inc.' },
    { symbol: 'RTX', name: 'Raytheon Technologies Corp' },
    { symbol: 'NFLX', name: 'Netflix Inc.' },
    { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
    { symbol: 'WFC', name: 'Wells Fargo & Company' },
    { symbol: 'UPS', name: 'United Parcel Service Inc.' },
    { symbol: 'MS', name: 'Morgan Stanley' },
    { symbol: 'INTC', name: 'Intel Corporation' },
    { symbol: 'QCOM', name: 'QUALCOMM Inc.' },
    { symbol: 'BA', name: 'Boeing Company' },
    { symbol: 'GS', name: 'Goldman Sachs Group Inc.' },
    { symbol: 'IBM', name: 'International Business Machines' },
    { symbol: 'CAT', name: 'Caterpillar Inc.' },
    { symbol: 'SPGI', name: 'S&P Global Inc.' },
    { symbol: 'AMGN', name: 'Amgen Inc.' },
    { symbol: 'DE', name: 'Deere & Company' },
    { symbol: 'PLD', name: 'Prologis Inc.' },
    { symbol: 'HON', name: 'Honeywell International Inc.' },
    { symbol: 'CVS', name: 'CVS Health Corporation' },
    { symbol: 'BLK', name: 'BlackRock Inc.' },
    { symbol: 'INTU', name: 'Intuit Inc.' },
    { symbol: 'LOW', name: "Lowe's Companies Inc." },
    { symbol: 'SCHW', name: 'Charles Schwab Corporation' },
    { symbol: 'AXP', name: 'American Express Company' },
    { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
    { symbol: 'ADI', name: 'Analog Devices Inc.' },
    { symbol: 'MDLZ', name: 'Mondelez International Inc.' },
    { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
    { symbol: 'AMAT', name: 'Applied Materials Inc.' },
    { symbol: 'GE', name: 'General Electric Company' },
    { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
    { symbol: 'MMC', name: 'Marsh & McLennan Companies' },
    { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
    { symbol: 'DUK', name: 'Duke Energy Corporation' },
    { symbol: 'CI', name: 'Cigna Corporation' },
    { symbol: 'TJX', name: 'TJX Companies Inc.' },
    { symbol: 'SYK', name: 'Stryker Corporation' },
    { symbol: 'C', name: 'Citigroup Inc.' },
    { symbol: 'BDX', name: 'Becton Dickinson and Company' },
    { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.' },
    { symbol: 'PGR', name: 'Progressive Corporation' },
    { symbol: 'CB', name: 'Chubb Limited' },
    { symbol: 'SO', name: 'Southern Company' },
    { symbol: 'MO', name: 'Altria Group Inc.' },
    { symbol: 'ZTS', name: 'Zoetis Inc.' },
    { symbol: 'REGN', name: 'Regeneron Pharmaceuticals' },
    { symbol: 'AON', name: 'Aon plc' },
    { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
    { symbol: 'MMM', name: '3M Company' },
    { symbol: 'BSX', name: 'Boston Scientific Corporation' },
    { symbol: 'NOC', name: 'Northrop Grumman Corporation' },
    { symbol: 'COP', name: 'ConocoPhillips' },
    { symbol: 'LRCX', name: 'Lam Research Corporation' },
    { symbol: 'PNC', name: 'PNC Financial Services Group' },
    { symbol: 'CSX', name: 'CSX Corporation' },
    { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
    { symbol: 'UNP', name: 'Union Pacific Corporation' },
    { symbol: 'ELV', name: 'Elevance Health Inc.' },
    { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
    { symbol: 'ABNB', name: 'Airbnb Inc.' },
    { symbol: 'TGT', name: 'Target Corporation' },
    { symbol: 'SBUX', name: 'Starbucks Corporation' },
    { symbol: 'ETN', name: 'Eaton Corporation plc' },
    { symbol: 'HCA', name: 'HCA Healthcare Inc.' },
    { symbol: 'GM', name: 'General Motors Company' },
    { symbol: 'F', name: 'Ford Motor Company' }
  ];